demo_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DemoBlogBundle:Default:index }
    
demo_blog_base_page:
    pattern:  /
    defaults: { _controller: DemoBlogBundle:Page:index }
    requirements:
      _method: GET
    
demo_blog_base_about:
    pattern:  /about
    defaults: { _controller: DemoBlogBundle:Page:about }
    requirements:
      _method: GET
