parameters:
    database_driver:   pdo_mssql
    database_host:     192.168.0.101
    database_port:     1433
    database_name:     testDb
    database_user:     test
    database_password: test-1

    mailer_transport:  gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: basicdemo13apr2013
    mailer_password: basicDemo

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
